//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogs.ModelDB
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// BlogCommentSet 
    /// </summary>
    [MetadataType(typeof(BlogCommentSetMet))]
    public partial class BlogCommentSet : MyModelBase 
    {
        /// <summary>
        /// 主键ID
        /// </summary>
        public int Id { get; set; }    
        /// <summary>
        /// 修改时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get { return base.CreateTime; } set { base.CreateTime = value; } }    
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> UpTime { get { return base.UpTime; } set { base.UpTime = value; } }    
        /// <summary>
        /// 是否不可用
        /// </summary>
        public bool IsDel { get { return base.IsDel; } set { base.IsDel = value; } }    
        /// <summary>
        /// 评论内容
        /// </summary>
        public string Content { get; set; }    
        /// <summary>
        /// (弃用)
        /// </summary>
        public string CommentSort { get; set; }    
        /// <summary>
        /// 
        /// </summary>
        public int CommentID { get; set; }    
        /// <summary>
        /// 
        /// </summary>
        public string ContentLevy { get; set; }    
        /// <summary>
        /// 博客用户ID
        /// </summary>
        public int BlogUsersId { get; set; }    
        /// <summary>
        /// 博客文章ID
        /// </summary>
        public int BlogsId { get; set; }    
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsInitial { get; set; }    
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ReplyUserID { get; set; }    
        /// <summary>
        /// 
        /// </summary>
        public string ReplyUserName { get; set; }    
    
        public virtual Blogs Blogs { get; set; }
        public virtual BlogUsersSet BlogUsersSet { get; set; }
    }
}
