//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogs.ModelDB
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// BlogTags 
    /// </summary>
    [MetadataType(typeof(BlogTagsMet))]
    public partial class BlogTags : MyModelBase 
    {
        public BlogTags()
        {
            this.Blogs = new HashSet<Blogs>();
        }
    
        /// <summary>
        /// 主键ID
        /// </summary>
        public int Id { get; set; }    
        /// <summary>
        /// tag标签名字
        /// </summary>
        public string TagName { get; set; }    
        /// <summary>
        /// 
        /// </summary>
        public string TagRemarks { get; set; }    
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get { return base.CreateTime; } set { base.CreateTime = value; } }    
        /// <summary>
        /// 修改时间
        /// </summary>
        public Nullable<System.DateTime> UpTime { get { return base.UpTime; } set { base.UpTime = value; } }    
        /// <summary>
        /// 是否不可用
        /// </summary>
        public bool IsDel { get { return base.IsDel; } set { base.IsDel = value; } }    
        /// <summary>
        /// 用户ID
        /// </summary>
        public int UsersId { get; set; }    
    
        public virtual BlogUsersSet BlogUsersSet { get; set; }
        public virtual ICollection<Blogs> Blogs { get; set; }
    }
}
