//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogs.ModelDB
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// BlogUsersSet 
    /// </summary>
    [MetadataType(typeof(BlogUsersSetMet))]
    public partial class BlogUsersSet : MyModelBase 
    {
        public BlogUsersSet()
        {
            this.BlogCommentSet = new HashSet<BlogCommentSet>();
            this.Blogs = new HashSet<Blogs>();
            this.BlogTags = new HashSet<BlogTags>();
            this.BlogTypes = new HashSet<BlogTypes>();
        }
    
        /// <summary>
        /// 主键ID
        /// </summary>
        public int Id { get; set; }    
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get { return base.CreateTime; } set { base.CreateTime = value; } }    
        /// <summary>
        /// 修改时间
        /// </summary>
        public Nullable<System.DateTime> UpTime { get { return base.UpTime; } set { base.UpTime = value; } }    
        /// <summary>
        /// 是否不可用
        /// </summary>
        public bool IsDel { get { return base.IsDel; } set { base.IsDel = value; } }    
        /// <summary>
        /// 用户名
        /// </summary>
        public string UserName { get; set; }    
        /// <summary>
        /// 密码
        /// </summary>
        public string UserPass { get; set; }    
        /// <summary>
        /// 别名昵称
        /// </summary>
        public string UserNickname { get; set; }    
        /// <summary>
        /// 邮箱
        /// </summary>
        public string UserMail { get; set; }    
        /// <summary>
        /// 是否锁定
        /// </summary>
        public bool IsLock { get; set; }    
        /// <summary>
        /// 用户头像
        /// </summary>
        public string UserImage { get; set; }    
    
        public virtual ICollection<BlogCommentSet> BlogCommentSet { get; set; }
        public virtual ICollection<Blogs> Blogs { get; set; }
        public virtual ICollection<BlogTags> BlogTags { get; set; }
        public virtual ICollection<BlogTypes> BlogTypes { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
