//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogs.ModelDB
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 博客文章主表 
    /// </summary>
    [MetadataType(typeof(BlogsMet))]
    public partial class Blogs : MyModelBase 
    {
        public Blogs()
        {
            this.BlogCommentSet = new HashSet<BlogCommentSet>();
            this.BlogTags = new HashSet<BlogTags>();
            this.BlogTypes = new HashSet<BlogTypes>();
            this.BlogReadInfo = new HashSet<BlogReadInfo>();
        }
    
        /// <summary>
        /// 主键ID
        /// </summary>
        public int Id { get; set; }    
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get { return base.CreateTime; } set { base.CreateTime = value; } }    
        /// <summary>
        /// 修改时间
        /// </summary>
        public Nullable<System.DateTime> UpTime { get { return base.UpTime; } set { base.UpTime = value; } }    
        /// <summary>
        /// 是否不可用
        /// </summary>
        public bool IsDel { get { return base.IsDel; } set { base.IsDel = value; } }    
        /// <summary>
        /// 文章内容
        /// </summary>
        public string BlogContent { get; set; }    
        /// <summary>
        /// 
        /// </summary>
        public string BlogRemarks { get; set; }    
        /// <summary>
        /// 文章标题
        /// </summary>
        public string BlogTitle { get; set; }    
        /// <summary>
        /// 文章url
        /// </summary>
        public string BlogUrl { get; set; }    
        /// <summary>
        /// 是否是转发文章
        /// </summary>
        public Nullable<bool> IsForwarding { get; set; }    
        /// <summary>
        /// 博客创建时间
        /// </summary>
        public Nullable<System.DateTime> BlogCreateTime { get; set; }    
        /// <summary>
        /// 博客修改时间
        /// </summary>
        public Nullable<System.DateTime> BlogUpTime { get; set; }    
        /// <summary>
        /// 用户ID（外键）
        /// </summary>
        public int UsersId { get; set; }    
        /// <summary>
        /// 文章阅读量
        /// </summary>
        public Nullable<int> BlogReadNum { get; set; }    
        /// <summary>
        /// 转发原链接
        /// </summary>
        public string BlogForUrl { get; set; }    
        /// <summary>
        /// 是否显示在首页
        /// </summary>
        public Nullable<bool> IsShowHome { get; set; }    
        /// <summary>
        /// 是否显示在个人主页
        /// </summary>
        public Nullable<bool> IsShowMyHome { get; set; }    
        /// <summary>
        /// 此博客文章的评论数
        /// </summary>
        public Nullable<int> BlogCommentNum { get; set; }    
    
        public virtual ICollection<BlogCommentSet> BlogCommentSet { get; set; }
        public virtual BlogUsersSet BlogUsersSet { get; set; }
        public virtual ICollection<BlogTags> BlogTags { get; set; }
        public virtual ICollection<BlogTypes> BlogTypes { get; set; }
        public virtual ICollection<BlogReadInfo> BlogReadInfo { get; set; }
    }
}
