//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogs.ModelDB
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 博客阅读信息 主要用来统计阅读量 
    /// </summary>
    [MetadataType(typeof(BlogReadInfoMet))]
    public partial class BlogReadInfo : MyModelBase 
    {
        /// <summary>
        /// 主键ID
        /// </summary>
        public int Id { get; set; }    
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get { return base.CreateTime; } set { base.CreateTime = value; } }    
        /// <summary>
        /// 修改时间
        /// </summary>
        public Nullable<System.DateTime> UpTime { get { return base.UpTime; } set { base.UpTime = value; } }    
        /// <summary>
        /// 是否不可用
        /// </summary>
        public bool IsDel { get { return base.IsDel; } set { base.IsDel = value; } }    
        /// <summary>
        /// 阅读客户端标识
        /// </summary>
        public string MD5 { get; set; }    
        /// <summary>
        /// 阅读统计最后有效时间
        /// </summary>
        public System.DateTime LastTime { get; set; }    
        /// <summary>
        /// 博客文章ID（外键）
        /// </summary>
        public int BlogsId { get; set; }    
    
        public virtual Blogs Blogs { get; set; }
    }
}
