//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogs.ModelDB
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 用户详细信息 
    /// </summary>
    [MetadataType(typeof(UserInfoMet))]
    public partial class UserInfo : MyModelBase 
    {
        public UserInfo()
        {
            this.BlogUpNum = 0;
        }
    
        /// <summary>
        /// 主键ID
        /// </summary>
        public int Id { get; set; }    
        /// <summary>
        /// 年龄
        /// </summary>
        public string Age { get; set; }    
        /// <summary>
        /// 性别
        /// </summary>
        public string Sex { get; set; }    
        /// <summary>
        /// 爱好
        /// </summary>
        public string Hobby { get; set; }    
        /// <summary>
        /// 个人简介
        /// </summary>
        public string Profile { get; set; }    
        /// <summary>
        /// 博客最后更新时间
        /// </summary>
        public Nullable<System.DateTime> BlogLastUpTime { get; set; }    
        /// <summary>
        /// 今日更新博客数量
        /// </summary>
        public int BlogUpNum { get; set; }    
        /// <summary>
        /// 是否不可用
        /// </summary>
        public bool IsDel { get { return base.IsDel; } set { base.IsDel = value; } }    
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get { return base.CreateTime; } set { base.CreateTime = value; } }    
        /// <summary>
        /// 修改时间
        /// </summary>
        public Nullable<System.DateTime> UpTime { get { return base.UpTime; } set { base.UpTime = value; } }    
        /// <summary>
        /// 是否禁用默认主题样式（PC）
        /// </summary>
        public Nullable<bool> IsDisCSS { get; set; }    
        /// <summary>
        /// 是否在其他用户页面启用自定义主题样式（PC）
        /// </summary>
        public Nullable<bool> IsShowCSS { get; set; }    
        /// <summary>
        /// (弃用)
        /// </summary>
        public Nullable<bool> IsShowHTML { get; set; }    
        /// <summary>
        /// （弃用）
        /// </summary>
        public Nullable<bool> IsShowJS { get; set; }    
        /// <summary>
        /// 是否在其他用户页面启用自定义主题样式（移动端）
        /// </summary>
        public Nullable<bool> IsShowMCSS { get; set; }    
        /// <summary>
        /// 是否禁用默认主题样式（移动端）
        /// </summary>
        public Nullable<bool> IsDisMCSS { get; set; }    
        /// <summary>
        /// 博客主题
        /// </summary>
        public string BlogTheme { get; set; }    
    
        public virtual BlogUsersSet BlogUsersSet { get; set; }
    }
}
