//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAdvanced
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcAdvancedEntities : DbContext
    {
        public MvcAdvancedEntities()
            : base("name=MvcAdvancedEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
  
        public DbSet<Employee> Employees { get; set; }
        public DbSet<EmpRole> EmpRoles { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
