//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autofac.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VehicleCheckDBEntities : DbContext
    {
        public VehicleCheckDBEntities()
            : base("name=VehicleCheckDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Sys_Roles> Sys_Roles { get; set; }
      //  public DbSet<Sys_User> Sys_User { get; set; }
        public DbSet<Sys_User_Roles> Sys_User_Roles { get; set; }
    }
}
