//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autofac.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string UserTrueName { get; set; }
        public string Password { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Code { get; set; }
        public string PreIpAddress { get; set; }
        public Nullable<System.DateTime> PreDate { get; set; }
        public string LastIpAddress { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<short> Status { get; set; }
    }
}
