DECLARE @USERINFO_TEMP TABLE(
	[ID] BIGINT,
	[ACCOUNT] NVARCHAR(50) NOT NULL,
	[USERPASSWORD] NVARCHAR(50) NOT NULL,
	[NICKNAME] NVARCHAR(30) NULL,
	[GENDER] BIT NULL,
	[COMPANYNAME] NVARCHAR(50) NULL,
	[USERADDRESS] NVARCHAR(100) NULL,
	[REMARK] NVARCHAR(100) NULL)
DECLARE @USERINFO_ID BIGINT;
DECLARE @ACCOUNT_TYPE INT ;

	SET @ACCOUNT_TYPE = 1 --'TEST VALUE '


	BEGIN TRAN
		BEGIN TRY

			INSERT INTO [dbo].[UserInfo]
			([ACCOUNT]
			   ,[USERPASSWORD]
			   ,[NICKNAME]
			   ,[GENDER]
			   ,[COMPANYNAME]
			   ,[USERADDRESS]
			   ,[REMARK])
			 OUTPUT INSERTED.* INTO @USERINFO_TEMP 
			 VALUES(
			 '111'
			 ,'111'
			 ,'111'
			 ,NULL
			 ,NULL
			 ,NULL
			 ,NULL);
			 PRINT @USERINFO_ID;
			 SELECT  @USERINFO_ID =ID  FROM @USERINFO_TEMP
			 PRINT @USERINFO_ID;
			 INSERT INTO [DBO].[UserInfo_AccountType_Mapping] output Inserted.* VALUES(@USERINFO_ID,@ACCOUNT_TYPE)

			 COMMIT

			 SELECT * FROM @USERINFO_TEMP ;

		END TRY
		BEGIN CATCH
			THROW
			RETURN 
		END CATCH
GO

--SELECT * FROM [UserInfo];
--SELECT * FROM [UserInfo_AccountType_Mapping];


--TRUNCATE TABLE [UserInfo];
--TRUNCATE TABLE [UserInfo_AccountType_Mapping];


SELECT 
		 U.ID
		,U.ACCOUNT
		,U.NICKNAME
		,U.GENDER
		,U.COMPANYNAME
		,U.USERADDRESS
		,U.REMARK
		
		FROM USERINFO AS U
			INNER JOIN USERINFO_ACCOUNTTYPE_MAPPING AS UM
			ON U.ID = UM.USERINFO_ID
			WHERE 1 <>2
			AND UserAccount_Type =0 
		ORDER BY ID 
		OFFSET 0 ROWS
		FETCH NEXT 10 ROWS ONLY;
		
		select * from userinfo
		SELECT * FROM USERINFO_ACCOUNTTYPE_MAPPING


		--alter table [UserInfo_AccountType_Mapping]
		--	alter column UserAccount_Type int null