DECLARE @USERINFO_TMP TABLE(USERINFO_ID BIGINT);
DECLARE @USERINFO_ID BIGINT;
DECLARE @ACCOUNT_TYPE INT ;
DECLARE @SQL VARCHAR(300)

	SET @SQL =N'INSERT INTO [DBO].[UserInfo_AccountType_Mapping](@USERINFO_ID,@ACCOUNT_TYPE)';
	SET @ACCOUNT_TYPE = 1 --'TEST VALUE '
INSERT INTO [dbo].[UserInfo]
		([ACCOUNT]
           ,[USERPASSWORD]
           ,[NICKNAME]
           ,[GENDER]
           ,[COMPANYNAME]
           ,[USERADDRESS]
           ,[REMARK])
		 OUTPUT INSERTED.ID INTO @USERINFO_TMP 
		 VALUES(
		 '111'
		 ,'111'
		 ,'111'
		 ,NULL
		 ,NULL
		 ,NULL
		 ,NULL);
		 PRINT @SQL;
		 PRINT @USERINFO_ID;
		 SELECT  @USERINFO_ID =USERINFO_ID  FROM @USERINFO_TMP
		 PRINT @USERINFO_ID;
		-- EXEC SP_EXECUTESQL @SQL,N'@USERINFO_ID BIGINT ,@ACCOUNT_TYPE INT',@USERINFO_ID,@ACCOUNT_TYPE ;
		
		 INSERT INTO [DBO].[UserInfo_AccountType_Mapping] VALUES(@USERINFO_ID,@ACCOUNT_TYPE)
GO




--SELECT COUNT(1) FROM [UserInfo]

--TRUNCATE TABLE UserInfo
--TRUNCATE TABLE [UserInfo_AccountType_Mapping]

SELECT * FROM UserInfo ;
SELECT * FROM [UserInfo_AccountType_Mapping];

